# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='mymodel',
            name='detail',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='sample1.MyDetailModel'),
        ),
    ]
